<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-06-27T12:18:06Z" name="tests" finished-at="2019-06-27T12:19:25Z" duration-ms="79154">
    <groups>
    </groups>
    <test started-at="2019-06-27T12:18:06Z" name="tests" finished-at="2019-06-27T12:19:25Z" duration-ms="79154">
      <class name="Tests">
        <test-method is-config="true" signature="setUp()[pri:0, instance:Tests@242b6e1a]" started-at="2019-06-27T12:18:06Z" name="setUp" finished-at="2019-06-27T12:18:09Z" duration-ms="3022" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:Tests@242b6e1a]" started-at="2019-06-27T12:18:09Z" name="beforeTest" finished-at="2019-06-27T12:18:09Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="test001_logowanie()[pri:1, instance:Tests@242b6e1a]" started-at="2019-06-27T12:18:10Z" name="test001_logowanie" description="Logowanie" finished-at="2019-06-27T12:18:23Z" duration-ms="13805" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test001_logowanie -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:Tests@242b6e1a]" started-at="2019-06-27T12:18:23Z" name="beforeTest" finished-at="2019-06-27T12:18:23Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="test002_fillExpertsApplication()[pri:1, instance:Tests@242b6e1a]" started-at="2019-06-27T12:18:23Z" name="test002_fillExpertsApplication" finished-at="2019-06-27T12:18:28Z" duration-ms="5083" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[cannot click on element]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: cannot click on element
at org.testng.Assert.fail(Assert.java:96)
at utils.Utils.safeClick(Utils.java:65)
at pages.ExpertsApplication.clickPolishLanguageCheckbox(ExpertsApplication.java:82)
at Tests.test002_fillExpertsApplication(Tests.java:105)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test002_fillExpertsApplication -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:Tests@242b6e1a]" started-at="2019-06-27T12:18:28Z" name="beforeTest" finished-at="2019-06-27T12:18:28Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="test003_fillPolishLanguagePromotion()[pri:1, instance:Tests@242b6e1a]" started-at="2019-06-27T12:18:28Z" name="test003_fillPolishLanguagePromotion" finished-at="2019-06-27T12:19:25Z" duration-ms="56426" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test003_fillPolishLanguagePromotion -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Tests@242b6e1a]" started-at="2019-06-27T12:19:25Z" name="teardown" finished-at="2019-06-27T12:19:25Z" duration-ms="569" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- Tests -->
    </test> <!-- tests -->
  </suite> <!-- tests -->
</testng-results>
